//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRSDBEntities : DbContext
    {
        public SRSDBEntities()
            : base("name=SRSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Departments> Departments1 { get; set; }
        public virtual DbSet<Instructors> Instructors1 { get; set; }
        public virtual DbSet<Registrations> Registrations1 { get; set; }
        public virtual DbSet<Students> Students1 { get; set; }
        public virtual DbSet<StudyTerms> StudyTerms1 { get; set; }
        public virtual DbSet<TAAssignments> TAAssignments1 { get; set; }
        public virtual DbSet<TAGraders> TAGraders1 { get; set; }
        public virtual DbSet<TeachingAssignments> TeachingAssignments1 { get; set; }
    }
}
