//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAAssignment
    {
        public string TAAssignmentID { get; set; }
        public string TAID { get; set; }
        public string CourseID { get; set; }
        public string TermID { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual StudyTerm StudyTerm { get; set; }
        public virtual TAGrader TAGrader { get; set; }
    }
}
