//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGrader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAGrader()
        {
            this.TAAssignments = new HashSet<TAAssignment>();
        }
    
        public string TAID { get; set; }
        public string TAFirstName { get; set; }
        public string TALastName { get; set; }
        public string TAPhone { get; set; }
        public string TAEmail { get; set; }
        public string DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAAssignment> TAAssignments { get; set; }
    }
}
